---
---

# [Developing Data Products](index.html)

## Instructor

- [Brian Caffo](http://www.bcaffo.com/)

## Class Website

- [Developing Data Products on Coursera.org](https://www.coursera.org/learn/data-products)

## Textbook

- [Developing Data Products in R](https://leanpub.com/ddp)


## Course Materials

| Week/Lecture  | Lecture  |  Video | Notes | Code |
|:------------|:------------|:------------|:------------|:------------|
| 1/1 | Welcome | --- | [html](welcome.html) [pdf](welcome.pdf)| --- |
| 1/2 | Syllabus | --- | [html](syllabus.html) [pdf](syllabus.pdf)| --- |
| 1/3 | Book: Developing Data Products in R | --- | [html](book.html) [pdf](book.pdf) | --- |
| 1/4 | Data Science Specialization Community Site | --- | [html](community.html) [pdf](community.pdf) | --- |
| 1/5 | Shiny: Reading | --- | [html](shiny.html) [pdf](shiny.pdf)| --- |
| 1/6 | Shiny: Part 1 | Part [1][shiny11] [2][shiny12] [3][shiny13] [4][shiny14] [5][shiny15] | [html](./Shiny_Part_1/Shiny_Part_1.html) [pdf](./Shiny_Part_1/Shiny_Part_1.pdf)| --- |
| 1/7 | Shiny: Part 2 | Part [1][shiny21] [2][shiny22] [3][shiny23] [4][shiny24] [5][shiny25] [6][shiny26] | [html](./Shiny_Part_2/Shiny_Part_2.html) [pdf](./Shiny_Part_2/Shiny_Part_2.pdf)| --- |
| 1/8 | Shiny Gadgets | --- | [html](./Shiny_Gadgets/Shiny_Gadgets.html) [pdf](./Shiny_Gadgets/Shiny_Gadgets.pdf)| --- |
| 1/9 | shinyapps.io Project | --- | [html](shinyproject.html) [pdf](shinyproject.pdf)| --- |
| 1/10 | GoogleVis | --- | [html](./googleVis/googleVis.html) [pdf](./googleVis/googleVis.pdf)| --- |
| 1/11 | Plotly | --- | [html](./plotly/plotly.html) [pdf](./plotly/plotly.pdf)| --- |
| --- | --- | --- | --- | --- |
| 2/1 | R Markdown | --- | [html](./R_Markdown/R_Markdown.html) [pdf](./R_Markdown/R_Markdown.pdf)| --- |
| 2/2 | Sharing R Markdown Documents | --- | [html](./sharingrmd.html) [pdf](./sharingrmd.pdf)| --- |
| 2/3 | Leaflet | --- | [html](./leaflet/leaflet.html) [pdf](./leaflet/leaflet.pdf)| --- |
| --- | --- | --- | --- | --- |
| 3/1 | R Packages | --- | [html](./RPackages/rpackages.html) [pdf](./RPackages/rpackages.pdf)| --- |
| 3/2 | Classes & Methods | --- | [html](./Classes_and_Methods/Classes_and_Methods.html) [pdf](./Classes_and_Methods/Classes_and_Methods.pdf)| --- |
| --- | --- | --- | --- | --- |
| 4/1 | Swirl Courses | --- | [html](./swirl/swirl.html) [pdf](./swirl/swirl.pdf)| --- |

## Resources

- [Installing R for Windows](https://www.youtube.com/watch?v=LII6of-5Odw)
- [Installing R for Mac](https://www.youtube.com/watch?v=xokJUwn0mis)
- [Installing RStudio Mac](https://www.youtube.com/watch?v=JbTMvQ-SbvQ)

- [Rstudio](http://www.rstudio.com/), [R project](http://www.r-project.org/)
- [Rstudio's cheatsheets](http://www.rstudio.com/resources/cheatsheets/) 

[shiny11]: https://drive.google.com/open?id=0B4QrfwPyx_SQcUdiWXRNa0Rza0U
[shiny12]: https://drive.google.com/open?id=0B4QrfwPyx_SQeXlPSjQyaTcxRTA
[shiny13]: https://drive.google.com/open?id=0B4QrfwPyx_SQZHBVZThHaWhFRzg
[shiny14]: https://drive.google.com/open?id=0B4QrfwPyx_SQdDBPRVVROG9JS2M
[shiny15]: https://drive.google.com/open?id=0B4QrfwPyx_SQbUxkS2w3Wnhybm8
[shiny21]: https://drive.google.com/open?id=0B4QrfwPyx_SQLU9BcUtZbFF5Rnc
[shiny22]: https://drive.google.com/open?id=0B4QrfwPyx_SQZGw1aW1FenVSQm8
[shiny23]: https://drive.google.com/open?id=0B4QrfwPyx_SQQ25nZUxiZXVjdTQ
[shiny24]: https://drive.google.com/open?id=0B4QrfwPyx_SQcllJX1ZETVNXU2M
[shiny25]: https://drive.google.com/open?id=0B4QrfwPyx_SQYldUdjdLYkt2RlU
[shiny26]: https://drive.google.com/open?id=0B4QrfwPyx_SQUnVMQ0lSVkNJY0k
[shinyg1]: https://drive.google.com/open?id=0B4QrfwPyx_SQNHFIckl2NDJzalk
[shinyg2]: https://drive.google.com/open?id=0B4QrfwPyx_SQT1A4U0dwTVpkbTQ
[shinyg3]: https://drive.google.com/open?id=0B4QrfwPyx_SQZnNqOEcwOF9lMFk

